import pandas as pd
from snakemake.utils import validate, min_version
import os.path as path

# ==============================================================================
# Configuration
# ==============================================================================
configfile: "config.yaml"
validate(config, schema="../schemas/config.schema.yaml")

samples = pd.read_table(config["samples"]).set_index("sample", drop=False)
validate(samples, schema="../schemas/samples.schema.yaml")

user_bed_file = pd.read_table(config["user_bed_file"], dtype=str),index_col=False)
validate(user_bed_file, schema="../schemas/user_bed_file.schema.yaml")


REPORT_DIR = "Reports"
FASTQ_DIR = "FASTQs"
TRIM_DIR = "Trimmed" 
ALIGN_DIR = "Aligned"
PEAK_DIR = "Peaks"
ANNO_DIR = "Annotation"
R_DIR = "R_analysis"


BWT2_IDX = config["BWT2_IDX"]

READS = [1, 2]
CHR_REGEX = "^chr[0-9]{0,3}[XYM]?\\t"

# ==============================================================================
# Meta Rules
# ==============================================================================
rule all:
    input:
        # GENCODE annotations
#        path.join(ANNO_DIR, "gencode.v{GENCODE_VERSION}.annotation.gff3.gz"),
        # FastQC reports
        expand(
            path.join(REPORT_DIR, "{sample}_R{read}_fastqc.{ext}"),
            sample=SAMPLES, read=READS, ext=["html", "zip"]
        ),
        # Trimming reports
        expand(
            path.join(REPORT_DIR, "{sample}_R{read}.trimming_report.txt"),
            sample=SAMPLES, read=READS
        ),
        expand(
            path.join(TRIM_DIR, "{sample}_R{read}.trimmed.fastq.gz"),
            sample=SAMPLES, read=READS
        ),
        # Bowtie2 alignment output files
        expand(path.join(ALIGN_DIR, "{sample}.filtered.dedup.sorted.bam"), sample=SAMPLES),
        expand(path.join(ALIGN_DIR, "{sample}.filtered.dedup.sorted.bam.bai"), sample=SAMPLES),
        # Peaks called by MACS2
        expand(
            path.join(PEAK_DIR, "{sample}_peaks.filtered.narrowPeak"),
            sample=SAMPLES
        ),
        

rule qc_check:
	input:
		# FRiP calculations
        path.join(REPORT_DIR, "quality_scores_frip.tsv"),
        

rule R_analysis:
    input:
        # Number of reads per region
        path.join(REPORT_DIR, "reads-in-control-regions.tsv"),
       	# bedfile statistics
	path.join(R_DIR, "bedfile_statistics.pdf"),
	# GeneMatching_All_OncoSuppressor
	path.join(R_DIR, "Matching_genes_proximity_oncogene.txt"),
        path.join(R_DIR, "Matching_genes_tumor_suppressor.txt"),
        #JaccardSim_QueryBed_To_TCGAPeaks
        path.join(R_DIR, config["JaccardSim"]["sample_name"]+".pdf"),
        path.join(R_DIR, "Mostsimilar_tissue_Top"+config["JaccardSim"]["top_SamNum"]+"samples.csv"),
        path.join(R_DIR, "Phenotypic_info_Top"+config["JaccardSim"]["top_SamNum"]+"samples.csv"),



# ==============================================================================
# Rules
# ==============================================================================
rule fastqc:
    input:
        path.join(FASTQ_DIR, "{fastq}.fastq.gz")
    output:
        path.join(REPORT_DIR, "{fastq}_fastqc.html"),
        path.join(REPORT_DIR, "{fastq}_fastqc.zip")
    shell:
        "fastqc {input} -o {REPORT_DIR}"

rule trim_galore:
    input:
        path.join(FASTQ_DIR, "{sample}_R1.fastq.gz"),
        path.join(FASTQ_DIR, "{sample}_R2.fastq.gz")
    output:
        path.join(TRIM_DIR, "{sample}_R1_val_1.fq.gz"),
        path.join(TRIM_DIR, "{sample}_R2_val_2.fq.gz"),
        path.join(TRIM_DIR, "{sample}_R1.fastq.gz_trimming_report.txt"),
        path.join(TRIM_DIR, "{sample}_R2.fastq.gz_trimming_report.txt"),
    params:
        "--gzip --paired -q 30"
    shell:
        "trim_galore {params} -o {TRIM_DIR} {input}"

rule rename_trim_galore:
    input:
        fq1 = path.join(TRIM_DIR, "{sample}_R1_val_1.fq.gz"),
        fq2 = path.join(TRIM_DIR, "{sample}_R2_val_2.fq.gz"),
        rp1 = path.join(TRIM_DIR, "{sample}_R1.fastq.gz_trimming_report.txt"),
        rp2 = path.join(TRIM_DIR, "{sample}_R2.fastq.gz_trimming_report.txt"),
    output:
        fq1 = path.join(TRIM_DIR, "{sample}_R1.trimmed.fastq.gz"),
        fq2 = path.join(TRIM_DIR, "{sample}_R2.trimmed.fastq.gz"),
        rp1 = path.join(REPORT_DIR, "{sample}_R1.trimming_report.txt"),
        rp2 = path.join(REPORT_DIR, "{sample}_R2.trimming_report.txt"),
    run:
        commands = [
            "mv {input.fq1} {output.fq1}",
            "mv {input.fq2} {output.fq2}",
            "mv {input.rp1} {output.rp1}",
            "mv {input.rp2} {output.rp2}",
       ]
        command_string = "; ".join(commands)
        shell(command_string)

rule align:
    input:
        path.join(TRIM_DIR, "{sample}_R1.trimmed.fastq.gz"),
        path.join(TRIM_DIR, "{sample}_R2.trimmed.fastq.gz")
    output:
        bam = protected(path.join(ALIGN_DIR, "{sample}.bam")),
        report = path.join(REPORT_DIR, "{sample}.alignment_report.txt")
    params:
        "-x {}".format(BWT2_IDX)
    shell:
        "bowtie2 {params} -1 {input[0]} -2 {input[1]} 2> {output.report} | samtools view -bS - > {output.bam}"

rule callpeaks:
    input:
        path.join(ALIGN_DIR, "{sample}.filtered.dedup.sorted.bam")
    output:
        path.join(PEAK_DIR, "{sample}_control_lambda.bdg"),
        temp(path.join(PEAK_DIR, "{sample}_peaks.narrowPeak")),
        path.join(PEAK_DIR, "{sample}_peaks.xls"),
        path.join(PEAK_DIR, "{sample}_summits.bed"),
        path.join(PEAK_DIR, "{sample}_treat_pileup.bdg")
    params:
        lambda wildcards:
            " ".join([
                "--outdir {}".format(PEAK_DIR),
                "-n {}".format(wildcards.sample),
                "-B",                               # store fragment pileup in bedGraph
                "-f BAM",                           # input format
                "-g 2.7e9",                         # genome size
                "--keep-dup all",                   # keep duplicates
                "--nomodel",  # bypass building shifting model
                "--nolambda",
                "--shift -75",                      # enriching for cutting sites, see example on GitHub MACS
                "--extsize 150",
                "--call-summits",                    # identify the summit of each peak
                "-q 0.01",                          # q-value filter
            ])
    shell:
        "macs2 callpeak -t {input} {params}"

rule filter_blacklist:
    input:
        blacklist = "../pipeline/static/hg38.blacklist.bed",
        peaks = path.join(PEAK_DIR, "{sample}_peaks.narrowPeak"),
    output:
        path.join(PEAK_DIR, "{sample}_peaks.filtered.narrowPeak"),
    shell:
        # remove blacklist regions and only keep canonical chromosomes
        "bedtools intersect -v -a {input.peaks} -b {input.blacklist} | awk '/{CHR_REGEX}/ {{print}}' | LC_COLLATE=C sort -k1,1 -k2,2n > {output}"

rule no_of_reads_per_region:
    input:
        script = "../pipeline/python/noOfRegionReads.py",
        user_bed_file = config["user_bed_file"],
        bams = expand(      # this `expand` command will make sure this rule waits for all BAMs to be available before running
            path.join(ALIGN_DIR, "{sample}.filtered.dedup.sorted.bam"),
            sample=SAMPLES
        ),
    output:
        path.join(REPORT_DIR, "reads-in-control-regions.tsv"),
    shell:
        "python {input.script} -a {input.user_bed_file} -b {input.bams} -o {output}"

##fraction of reads in peaks
rule frip:
    input:
    	script = "../pipeline/bash/calculateFrip.sh",
    output:
        path.join(REPORT_DIR, "quality_scores_frip.tsv")
    shell:
        "bash {input.script} {ALIGN_DIR} {PEAK_DIR} {output} {SAMPLES}"

###bedfile statistics
rule bed_stats:
    input:
    	script = "../pipeline/R/bedfile_statistics.R",
    	user_bed_file = config["user_bed_file"]
    output:
        path.join(R_DIR, "bedfile_statistics.pdf")
    shell:
        "Rscript {input.script} -f {input.user_bed_file} -o {output}"	

###GeneMatching_All_OncoSuppressor
rule GeneMatching_All_OncoSuppressor:
    input:
    	script = "../pipeline/R/GeneMatching_All_OncoSuppressor.R",
    	user_bed_file = config["user_bed_file"]
    output:
        path.join(R_DIR, "Matching_genes_proximity_oncogene.txt"),
        path.join(R_DIR, "Matching_genes_proximity_tumor_suppressor.txt")
    params:
        "-t "+config["GeneMatching"]["TSSDist"]
    shell:
        "Rscript {input.script} -f {input.user_bed_file} {params} -d {R_DIR}"

##JaccardSim_QueryBed_To_TCGAPeaks
rule JaccardSim_QueryBed_To_TCGAPeaks:
    input:
    	script = "../pipeline/R/JaccardSim_QueryBed_To_TCGAPeaks.R",
    	user_bed_file = "TCGA-2G-AAFM-01A_SigCut1.65_.bed",
    output:
        path.join(R_DIR, config["JaccardSim"]["sample_name"]+".pdf"),
        path.join(R_DIR, "Mostsimilar_tissue_Top"+config["JaccardSim"]["top_SamNum"]+"samples.csv"),
        path.join(R_DIR, "Phenotypic_info_Top"+config["JaccardSim"]["top_SamNum"]+"samples.csv"),
    params:
        "-t "+config["JaccardSim"]["top_SamNum"]+" -s "+config["JaccardSim"]["sample_name"]+" -c "+config["JaccardSim"]["tissue_name"]
    shell:
        "Rscript {input.script} -f {input.user_bed_file} {params} -d {R_DIR}"

 
# ==============================================================================
# Tools
# ==============================================================================
rule sort:
    input:
        "{file}.bam"
    output:
        "{file}.sorted.bam",
        "{file}.sorted.bam.bai"
    params:
        "--tmpdir . -p"
    shell:
        "sambamba sort {params} {input} -o {output}"

rule dedup:
    input:
        "{file}.bam"
    output:
        "{file}.dedup.bam"
    params:
        "-r -p --tmpdir ."
    shell:
        "sambamba markdup {params} {input} {output}"

rule keep_quality_alignments:
    input:
        "{file}.bam"
    output:
        "{file}.filtered.bam"
    params:
        filter = " and ".join([
            "not (unmapped or mate_is_unmapped)"
            "proper_pair",
            "mapping_quality >= 10"
        ]),
        other = " ".join([
            "-f bam",
            "-p"
        ])
    shell:
        "sambamba view -F '{params.filter}' {params.other} -o {output} {input}"
