$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  BWT2_IDX:
    type: string
  user_bed_file:
    type: string
  GeneMatching:
    type: object
    properties:
      TSSDist: 
        type: integer
  JaccardSim:
    type: object
    properties:
      top_SamNum:
        type: integer
      sample_name:
        type: string
      tissue_name:
        type: string

required:
  - samples
  - BWT2_IDX
